//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaLuan.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportDetail
    {
        public int ImportId { get; set; }
        public int TreeId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Cost { get; set; }
    
        public virtual Import Import { get; set; }
        public virtual Tree Tree { get; set; }
    }
}
