//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaLuan.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import
    {
        public Import()
        {
            this.ImportDetails = new HashSet<ImportDetail>();
        }
    
        public int ImportId { get; set; }
        public Nullable<System.DateTime> TimeChanged { get; set; }
        public Nullable<int> TotalCost { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual ICollection<ImportDetail> ImportDetails { get; set; }
    }
}
