//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaLuan.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tree
    {
        public int TreeId { get; set; }
        public string TreeName { get; set; }
        public Nullable<int> CatId { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
